codeland.html
Add sample markup to CodeLand page so that it'll be easier to style later.
=> Add sample markup to CodeLand page

README.md, banner.html, display_ad.html
Just added skeleton pages for the banner and side ad on the homepage
=> Skeletons for banner and display ad

banner.html, display_ad.html
Just adds links and embedded video to the skeleton banner and display ad.
=> Add links and video to skeletons

codeland.html
Updated responsive display to create height container on livestream video frame.
=> Refactor responsive display

codeland.html, codeland_schedule.json
For our rehearsal tomorrow all Connect links will have the same room but should work okay for the first trial run.
__Side Note:__ When seen locally the sidecar will show the navigation bar because the iframe is rendering a separate host (localhost vs dev.to), this won't/shouldn't happen in production 😄
=> Adds the rehearsal link for testing

banner.html
=> Add banner HTML content

codeland.html
- Fix menu display for static vs. fixed top bar configs
- Refactor panel header with explicit class names and `Crayons` styling
- Update `sidecar` panel shadows
=> Improve style fixes

README.md, codeland.html, codeland_now_playing.json, sample_schedule.rb
Woohoo: `codeland_now_playing.json` is no longer needed! This PR updates the JavaScript on `codeland.html` to update the now playing blocked based on the current browser's time and schedule data.
=> Autoupdate now playing based on schedule!

codeland.html
This PR has a couple fixes around link clicks.
I it's best if we first merge #25. After that I'll adapt and fix the conflicts, because that PR includes some changes to `updateTalkInfo()` function
=> Link fixes

codeland.html
- Add "See all" button & functionality to show only 6 event listings and expand to show all
- Update visual typography of event listings
See video: https://share.getcloudapp.com/P8ue7oEn
=> Update schedule section

codeland.html
=> Add now-playing styles

codeland.html, sample_schedule.rb
Fixes include:
- Overflowing text/elements in small screens when unauthenticated
- New calc is added for large screens (> 1280px) where the sidecar will take advantage of the large screen available
Video:
https://share.getcloudapp.com/GGuoJ4ln
Also added some code to randomly add Sponsors in `sample_schedule.rb`
=> Sidecar fixes

codeland.html
https://share.getcloudapp.com/QwulZ6O5
=> Add responsive 16:9 video display

codeland.html
=> Add sponsor logos

codeland.html
=> Update social rooms content

codeland.html
- Add padding to sidecar element for logged-out experience
- Bring back previously rolled-back updates in social-rooms
- Add border to sponsor items
=> Update sidecar padding and bring back previous rolled back updates

codeland.html
- Remove Mozilla
- Update HarperDB
- Add Digital Ocean and Stream
---
Add the following sponsors
=> Update sponsors and career fair

banner.html
[Video demo](https://share.getcloudapp.com/p9uP1jd8)
Related: https://3.basecamp.com/4435015/buckets/17165995/todos/2813929856
=> [DRAFT] Update banner with close-btn functionality

codeland.html
=> Add help text

codeland.html
`const` in this case is causing instantclick issues. Hiding broadcast which should not display on this page.
=> Update codeland for broadcast hide and const fix

banner.html
When banner is on page we can hide the broadcast
=> Broadcast does not need to be visible if banner

codeland.html
Disables hover/links on schedule if there isn't a URL associated with it:
=> Disable links if there's no url

codeland.html
Hide `See Discussion` button if there is no URL.
=> Check for url
